.TH notaflag 1
.SH NAME
notaflag - an application that is sadly, not a flag
.SH SYNOPSIS
.B notaflag
.SH DESCRIPTION
This app is cool.
But it would be cooler if it were a flag
.SH BUGS
.BR notaflag " is not a flag"
.RB " but this is a flag: jctf{f1n4LLy_f0uND_1T}"
.SH AUTHOR
Cool Person <coolperson@gmail.com>